name: Test workflow
on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Scripts
      uses: actions/checkout@v2

    - name: Dump context
      run: echo ${{ github.actor }}

    - name: Get secrets
      run: |
        echo '
        {
          "strutt": "$BENS_PAT",
          "Sourceless": "$LAURENCES_PAT"
        }
        ' | jq -r ."${{ github.actor }}" | wc -c
      env:
        BENS_PAT: ${{ secrets.BENS_PAT }}
        LAURENCES_PAT: ${{ secrets.LAURENCES_PAT }}
