name: Test workflow
on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Scripts
      uses: actions/checkout@v2

    - name: Email address of most recent user
      run: git log -1 --pretty=format:'%ae'
