name: Test workflow
on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Scripts
      uses: actions/checkout@v2

    - name:
      run: |
        export USERNAME=$(git log -1 --pretty=format:'%ae')
        echo '
        {
          "ben.strutt1@nhs.net": "${{ github.secrets.BENS_PAT }}",
          "laurence.smith@airelogic.com": "${{ github.secrets.LAURENCES_PAT }}"
        }
        ' | jq -r ."${USERNAME}"
