name: Test workflow
on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Scripts
      uses: actions/checkout@v2

    - name: Dump context
      run: echo ${{ github.actor }}

    - name: Get secrets
      env:
        BENS_PAT: ${{ secrets.BENS_PAT }}
        LAURENCES_PAT: ${{ secrets.LAURENCES_PAT }}
      run: |
        declare -A PATS
        PATS[strutt]="$BENS_PAT"
        PATS[Sourceless]="$LAURENCES_PAT"
        echo ${PATS[${{ github.actor }}]} | wc -c
