name: Test workflow
on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Scripts
      uses: actions/checkout@v2

    - name: Dump context
      run: echo ${{ github.actor }}

    - name:
      run: |
        echo '
        {
          "strutt": "${{ github.secrets.BENS_PAT }}",
          "Sourceless": "${{ github.secrets.LAURENCES_PAT }}"
        }
        ' | jq -r ."${{ github.actor }}"
